### ISSUE TITLE
NPM generator: package names error

### ISSUE THREAD

**Issue by DaJaime** [sse-labs/dgmf#1]
There's an error when **generating the npm graph,** you'll find this error at the end of the message.

The problem is that this "https://raw.githubusercontent.com/bconnorwhite/all-package-names/master/data/all.json?raw=true" URL returns "404: Not Found".
In fact, the repository owner of "all-package-names" has **removed the json file** and **replaced it with a .gz archive** to reduce its size.

I hotfixed this by replacing the URL line 16 of the "**NpmIdGenerator**" class with "https://raw.githubusercontent.com/bconnorwhite/all-package-names/2f4ce16fd68355fe366eab0abf37e97bd7cdd657/data/all.json?raw=true" (id of the last commit with the json file) and it seems to work.

The problem now is that we can't generate graphs more recent than this commit (Mar 31, 2023).

Thanks for your tool.

Error output:

> java -jar ./target/dgmf.jar start
> 12:48:52 [INFO ] [CommandUtilities] - Loaded configuration from system.properties
> 12:48:52 [INFO ] [StartCommand] - Initialise task
> 12:48:52 [INFO ] [StartCommand] - Started task with repository npm
> 12:48:53 [ERROR] [NpmIdGenerator] - Malformed GitHub response, cannot load package names
> 12:48:53 [ERROR] [Task] - => Mining of PackageIds for Repository npm failed <=
> 12:48:53 [ERROR] [ConsoleApplication] - Execution aborted due to errors
> 12:48:53 [INFO ] [ExceptionLogger] - Exception logs are empty

**Comment by johannesduesing** [comment]
Hi @DaJaime, 

thank you so much for letting us know about that change, so far we had not noticed that. I'll have a look into that, i guess it would be best to change the `NpmIdGenerator` so it downloads the `.gz` archive and unzips it - i'll get back to you once a solution is in place!

**Comment by johannesduesing** [comment]
We implemented a fix for this issue in #2 and merged the changes to `develop`. This should fix the issue, however, it does not work with the current `all.json.gz` because it [seems to be corrupted](https://github.com/bconnorwhite/all-package-names/issues/5). I added a configuration option to use a fixed commit, which allows you to use the latest *working* version of the `all.json.gz` file (for me commit `d3fea291938bb224d6cafa4190009b1bf4e45110` from two days ago is the latest one that works). Hopefully the next synchronization fixes the issue, then it should be fine to use the default behavior, which accesses the latest `all.json.gz` on the master branch.

For now i will close this issue, feel free to re-open if the problem persists. Thanks for your feedback!
